### ISSUE TITLE
Git/Github awaiting review

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/Reproducible-science-in-R#21]
Take a look at chapter six and tell me if it's bork.

**Comment by zachary-foster** [comment]
What do you think about combining the two conclusion sections into one?

 I am making a few minor changes on another branch and will send a PR soon (#25). I still need to get pandoc set up so that I can get the CSS classes for the images to apply, so borkness is still undetermined so far in that regard, but the content looks good. I will try to install pandoc and get back to you.

By the way, I had to look up "bork".

**Comment by zachary-foster** [comment]
I think this has been done now
